/**
 * Attendance Report Export Utilities
 * Generate CSV and PDF reports
 */

const PDFDocument = require('pdfkit');
const { createObjectCsvWriter } = require('csv-writer');
const path = require('path');
const fs = require('fs');

// Ensure reports directory exists
const reportsDir = path.join(__dirname, '../../data/reports');
if (!fs.existsSync(reportsDir)) {
  fs.mkdirSync(reportsDir, { recursive: true });
}

/**
 * Generate CSV Report
 */
async function generateCSVReport(attendanceData, filename) {
  try {
    const filepath = path.join(reportsDir, filename);
    
    const csvWriter = createObjectCsvWriter({
      path: filepath,
      header: [
        { id: 'student_id', title: 'Student ID' },
        { id: 'full_name', title: 'Student Name' },
        { id: 'email', title: 'Email' },
        { id: 'course_code', title: 'Course' },
        { id: 'session_date', title: 'Date' },
        { id: 'scan_time', title: 'Scan Time' },
        { id: 'attendance_status', title: 'Status' },
        { id: 'is_within_geofence', title: 'Within Geofence' },
        { id: 'gps_latitude', title: 'Latitude' },
        { id: 'gps_longitude', title: 'Longitude' },
      ],
    });

    await csvWriter.writeRecords(attendanceData);
    console.log(`✓ CSV report generated: ${filename}`);
    return filepath;
  } catch (err) {
    console.error('Error generating CSV:', err);
    throw new Error('Failed to generate CSV report');
  }
}

/**
 * Generate PDF Report
 */
async function generatePDFReport(attendanceData, reportTitle, filename) {
  return new Promise((resolve, reject) => {
    try {
      const filepath = path.join(reportsDir, filename);
      const doc = new PDFDocument({
        size: 'A4',
        margin: 40,
        bufferPages: true,
      });

      const stream = fs.createWriteStream(filepath);
      doc.pipe(stream);

      // Header
      doc.fontSize(24).font('Helvetica-Bold').text(reportTitle, { align: 'center' });
      doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toLocaleString()}`, {
        align: 'center',
      });
      doc.moveDown();

      // Summary stats
      const totalRecords = attendanceData.length;
      const presentCount = attendanceData.filter((r) => r.attendance_status === 'PRESENT').length;
      const absentCount = attendanceData.filter((r) => r.attendance_status === 'ABSENT').length;
      const attendanceRate = totalRecords > 0 ? ((presentCount / totalRecords) * 100).toFixed(2) : 0;

      doc.fontSize(12).font('Helvetica-Bold').text('Summary', { underline: true });
      doc.fontSize(10).font('Helvetica');
      doc.text(`Total Records: ${totalRecords}`);
      doc.text(`Present: ${presentCount}`);
      doc.text(`Absent: ${absentCount}`);
      doc.text(`Attendance Rate: ${attendanceRate}%`);
      doc.moveDown();

      // Table header
      doc.fontSize(11).font('Helvetica-Bold');
      const tableX = 40;
      const colWidths = { name: 100, course: 80, date: 70, status: 60, geofence: 60 };
      let y = doc.y;

      doc.text('Student', tableX, y);
      doc.text('Course', tableX + colWidths.name, y);
      doc.text('Date', tableX + colWidths.name + colWidths.course, y);
      doc.text('Status', tableX + colWidths.name + colWidths.course + colWidths.date, y);
      doc.text('Geofence', tableX + colWidths.name + colWidths.course + colWidths.date + colWidths.status, y);

      y += 20;
      doc.strokeColor('#cccccc').moveTo(tableX, y).lineTo(550, y).stroke();
      y += 10;

      // Table rows
      doc.fontSize(9).font('Helvetica');
      attendanceData.slice(0, 50).forEach((record) => {
        doc.text(record.full_name?.substring(0, 15) || 'N/A', tableX, y, { width: colWidths.name });
        doc.text(record.course_code || 'N/A', tableX + colWidths.name, y, {
          width: colWidths.course,
        });
        doc.text(
          new Date(record.session_date).toLocaleDateString(),
          tableX + colWidths.name + colWidths.course,
          y,
          { width: colWidths.date }
        );
        doc.text(record.attendance_status || 'N/A', tableX + colWidths.name + colWidths.course + colWidths.date, y, {
          width: colWidths.status,
        });
        doc.text(record.is_within_geofence ? 'Yes' : 'No', tableX + colWidths.name + colWidths.course + colWidths.date + colWidths.status, y, {
          width: colWidths.geofence,
        });

        y += 15;
        if (y > 750) {
          doc.addPage();
          y = 40;
        }
      });

      // Footer
      doc.fontSize(8).font('Helvetica').text('This is an automated report generated by Attendance Management System', {
        align: 'center',
        y: doc.page.height - 30,
      });

      doc.end();
      stream.on('finish', () => {
        console.log(`✓ PDF report generated: ${filename}`);
        resolve(filepath);
      });
      stream.on('error', reject);
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Generate Excel Report (CSV format)
 */
async function generateExcelReport(attendanceData, filename) {
  return generateCSVReport(attendanceData, filename);
}

/**
 * Get all reports
 */
function getAvailableReports() {
  try {
    const files = fs.readdirSync(reportsDir);
    return files.map((file) => ({
      name: file,
      path: path.join(reportsDir, file),
      size: fs.statSync(path.join(reportsDir, file)).size,
      createdAt: fs.statSync(path.join(reportsDir, file)).birthtime,
    }));
  } catch (err) {
    console.error('Error reading reports:', err);
    return [];
  }
}

/**
 * Download report file
 */
function downloadReport(filename) {
  const filepath = path.join(reportsDir, filename);
  if (fs.existsSync(filepath)) {
    return filepath;
  }
  return null;
}

/**
 * Delete report file
 */
function deleteReport(filename) {
  try {
    const filepath = path.join(reportsDir, filename);
    if (fs.existsSync(filepath)) {
      fs.unlinkSync(filepath);
      console.log(`✓ Report deleted: ${filename}`);
      return true;
    }
    return false;
  } catch (err) {
    console.error('Error deleting report:', err);
    return false;
  }
}

module.exports = {
  generateCSVReport,
  generatePDFReport,
  generateExcelReport,
  getAvailableReports,
  downloadReport,
  deleteReport,
  reportsDir,
};
